const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));
const date = (value) => value ? new Date(value).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

function createPurchaseConfirmationEmail({ student, course, transaction, enrollment, temporaryPassword }) {
  const transactionId = transaction.gatewayReference || transaction.transactionReference || transaction.purchaseId;
  const paidMinor = transaction.pricing?.paidAmountMinor;
  const paid = paidMinor != null ? Number(paidMinor) / 100 : Number(transaction.pricing?.paidAmount || 0);
  const greeting = escapeHtml(student.name || 'Student');
  const rawCourseName = course.name || 'Course';
  const courseName = escapeHtml(rawCourseName);
  const loginDetails = temporaryPassword
    ? `<div style="margin-top:18px;padding:14px 16px;border-radius:10px;background:#fff5e9;border:1px solid #f2cf9a"><strong style="color:#6d4d22">GS BY Anand Sir app login details / लॉगिन तपशील</strong><br/>Login email / लॉगिन ईमेल: ${escapeHtml(student.email)}<br/>Temporary password / तात्पुरता पासवर्ड: <strong>${escapeHtml(temporaryPassword)}</strong><br/><span style="color:#6f665b">Please change your password after you sign in. / लॉगिन केल्यानंतर पासवर्ड बदला.</span></div>`
    : '';
  const textLoginDetails = temporaryPassword ? `\n\nLogin details / लॉगिन तपशील\nLogin email / लॉगिन ईमेल: ${student.email}\nTemporary password / तात्पुरता पासवर्ड: ${temporaryPassword}\nPlease change your password after you sign in. / लॉगिन केल्यानंतर पासवर्ड बदला.` : '';
  return {
    subject: `Course activated / कोर्स सक्रिय — ${rawCourseName} | GS BY Anand Sir`,
    text: `Dear ${student.name || 'Student'},\n\nYour payment was successful and your course is now active.\nतुमचे पेमेंट यशस्वी झाले असून तुमचा कोर्स आता सक्रिय आहे.\n\nCourse name / कोर्सचे नाव: ${rawCourseName}\nAmount paid / भरलेली रक्कम: INR ${paid.toFixed(2)}\nReceipt number / पावती क्रमांक: ${transaction.receiptNumber}\nTransaction ID / व्यवहार क्रमांक: ${transactionId}\nValidity / वैधता: ${enrollment.validityDays} days (${date(enrollment.validFrom)} to ${date(enrollment.validUntil)})${textLoginDetails}\n\nYour course receipt with the course name and first-time login details is attached as a PDF.\nकोर्सचे नाव आणि प्रथम लॉगिन तपशील असलेली पावती PDF स्वरूपात जोडली आहे.`,
    html: `<div style="margin:0;padding:24px;background:#f6f1eb;font-family:Arial,sans-serif;color:#2b261f"><div style="max-width:620px;margin:auto;overflow:hidden;border-radius:18px;background:#fff;box-shadow:0 8px 28px rgba(43,38,31,.14)"><div style="padding:24px 28px;background:linear-gradient(135deg,#173f3b,#a87c43);color:#fff"><div style="display:inline-block;margin-right:10px;padding:8px 10px;border:1px solid rgba(255,255,255,.75);border-radius:10px;font-weight:800;letter-spacing:1px">GS</div><span style="font-size:20px;font-weight:800">GS BY Anand Sir</span><div style="margin-top:18px;font-size:13px;letter-spacing:1.3px">COURSE PURCHASE CONFIRMATION / कोर्स खरेदी पुष्टी</div></div><div style="padding:28px"><h1 style="margin:0 0 10px;font-size:23px;color:#2f5e58">Congratulations, ${greeting}! / अभिनंदन!</h1><p style="margin:0 0 22px;line-height:1.6">Your payment was successful. Your course is now active in the student app.<br/>तुमचे पेमेंट यशस्वी झाले असून तुमचा कोर्स आता विद्यार्थी अॅपमध्ये सक्रिय आहे.</p><div style="padding:18px;border-radius:12px;background:#f7f3ed"><div style="margin-bottom:12px;font-size:18px;font-weight:800;color:#2f5e58">Course name / कोर्सचे नाव: ${courseName}</div><table style="width:100%;border-collapse:collapse;font-size:14px"><tr><td style="padding:7px 0;color:#6f665b">Amount paid / भरलेली रक्कम</td><td style="padding:7px 0;text-align:right;font-weight:700">INR ${paid.toFixed(2)}</td></tr><tr><td style="padding:7px 0;color:#6f665b">Receipt number / पावती क्रमांक</td><td style="padding:7px 0;text-align:right;font-weight:700">${escapeHtml(transaction.receiptNumber)}</td></tr><tr><td style="padding:7px 0;color:#6f665b">Transaction ID / व्यवहार क्रमांक</td><td style="padding:7px 0;text-align:right;font-weight:700">${escapeHtml(transactionId)}</td></tr><tr><td style="padding:7px 0;color:#6f665b">Course validity / कोर्स वैधता</td><td style="padding:7px 0;text-align:right;font-weight:700">${enrollment.validityDays} days</td></tr><tr><td style="padding:7px 0;color:#6f665b">Access period / प्रवेश कालावधी</td><td style="padding:7px 0;text-align:right;font-weight:700">${date(enrollment.validFrom)} – ${date(enrollment.validUntil)}</td></tr></table></div>${loginDetails}<p style="margin:22px 0 0;line-height:1.55;color:#554c42">Your course receipt, including the course name and first-time login details, is attached as a PDF.<br/>कोर्सचे नाव आणि प्रथम लॉगिन तपशील असलेली पावती PDF स्वरूपात जोडली आहे.</p></div><div style="padding:16px 28px;background:#f7f3ed;color:#6f665b;font-size:12px">GS BY Anand Sir · Academy support and learning portal</div></div></div>`,
  };
}

module.exports = { createPurchaseConfirmationEmail };
